### ISSUE TITLE
About Code

### ISSUE THREAD

**Issue by 123456789asdfjkl** [BGU-CS-VIL/DiTAC#1]
Hi! Thank you for your great work! I want to know when the code will be released.

**Comment by freifeld** [comment]
Thank you very much @123456789asdfjkl  for your kind words. The code is coming soon.

**Comment by freifeld** [comment]
> Hi! Thank you for your great work! I want to know when the code will be released.

Thank you very much @123456789asdfjkl for your kind words. The code is coming soon.

**Comment by shahaffind** [comment]
Thank you for your interest.
We've uploaded the code :)
